version: '3'

services:
  frontend:
    build: ./FE
    ports:
      - 5173:5173
    depends_on:
      - api
  api:
    image: verglass/shop-api:1.0
    ports:
      - 3500:3500
    depends_on:
      - idp
  idp:
    image: quay.io/keycloak/keycloak:21.0.2
    command: 
      - start-dev
    ports:
      - 8080:8080
    volumes:
      - ./keycloak_data:/opt/keycloak/data
  